### ISSUE TITLE
where complete code and example for @app.login

### ISSUE THREAD

**Issue by bobwatcherx** [Daxexs/flet-easy#1]
is there code full example implement @app.login

thx

**Comment by Daxexs** [comment]
You can access the `page` parameter, with it you can access `page.client_storage` [more details here](https://flet.dev/docs/guides/python/client-storage), obtaining the value already registered, it makes a check with a database or any data management that you want to use, at the end it should return a boolean value.

**Comment by Daxexs** [comment]
> You can access the `page` parameter, with it you can access `page.client_storage` [more details here](https://flet.dev/docs/guides/python/client-storage), obtaining the value already registered, it makes a check with a database or any data management that you want to use, at the end it should return a boolean value.

**A basic example:**
```python
@app.login
async def login_x(page: ft.Page):
    username = await page.client_storage.get_async("login")
    if username is None:
          return False
    return True
```

**Comment by bobwatcherx** [comment]
can you give small example i not found solution

```
from flet import *

import flet_easy as fs

app = fs.FletEasy(
    route_init="/login",
    route_login="/login"
    )


@app.login
async def login_x(page: Page):
    username = await page.client_storage.get_async("login")
    if username is None:
          return False
    return True


@app.page(route="/dashboard",protected_route=True)
def index_page(data: fs.Datasy):
    page = data.page

    return View(
        route="/dashboard",
        controls=[
            Text("Dash",size=30)
        ]
        )

@app.page(route="/login")
def index_page(data: fs.Datasy):
    page = data.page

    return View(
        route="/login",
        controls=[
            Text("login",size=30),
            ElevatedButton("go",on_click=lambda _: page.go("/dashboard"))
        ]
        )



app.run()
```

**Comment by Daxexs** [comment]
> ¿Puedes dar un pequeño ejemplo? No encontré la solución.
> 
> ```
> from flet import *
> 
> import flet_easy as fs
> 
> app = fs.FletEasy(
>     route_init="/login",
>     route_login="/login"
>     )
> 
> 
> @app.login
> async def login_x(page: Page):
>     username = await page.client_storage.get_async("login")
>     if username is None:
>           return False
>     return True
> 
> 
> @app.page(route="/dashboard",protected_route=True)
> def index_page(data: fs.Datasy):
>     page = data.page
> 
>     return View(
>         route="/dashboard",
>         controls=[
>             Text("Dash",size=30)
>         ]
>         )
> 
> @app.page(route="/login")
> def index_page(data: fs.Datasy):
>     page = data.page
> 
>     return View(
>         route="/login",
>         controls=[
>             Text("login",size=30),
>             ElevatedButton("go",on_click=lambda _: page.go("/dashboard"))
>         ]
>         )
> 
> 
> 
> app.run()
> ```

A basic example, still missing data validations for security, remember to use `async` if all pages are asynchronous, i.e. when executing `app.run_async()`. Also, first store data with `client_storage.set()` and then retrieve the `login` decorator when performing validations. 

```python
import flet as ft
import flet_easy as fs

app = fs.FletEasy(
    route_init="/login",
    route_login="/login"
)

db = [] # Database


@app.login
def login_x(page: ft.Page):
    username = page.client_storage.get("login")
    if username is not None:  # We check if a value exists with the key login
        # We verify if the username that is stored in the browser is in the simulated database.
        if username in db:
            return True
    return False


@app.page(route="/dashboard", proctect_route=True)
def dashboard_page(data: fs.Datasy):
    page = data.page
    page.title = "Dashboard"

    def logaut(e):
        # We delete the key that we have previously registered
        page.client_storage.remove('login')
        page.go('/login')

    return ft.View(
        route="/dashboard",
        controls=[
            ft.Text("Dash", size=30),
            ft.ElevatedButton('Logaut', on_click=logaut)
        ]
    )


@app.page(route="/login")
def login_page(data: fs.Datasy):
    page = data.page
    page.title = "Login"

    # create login stored user
    username = ft.TextField(label='Username')

    def store_login(e):
        """ First the values must be stored in the browser, then in the login decorator the value must be retrieved through the key used and then validations must be used. """
        page.client_storage.set(key='login', value=username.value)

        db.append(username.value)  # We add to the simulated database

    return ft.View(
        route="/login",
        controls=[
            ft.Text("login", size=30),
            username,
            ft.ElevatedButton('store login in browser', on_click=store_login),
            ft.ElevatedButton("go", on_click=lambda _: page.go("/dashboard"))
        ]
    )


app.run()

```
