### ISSUE TITLE
What are the best practices for a side tab bar

### ISSUE THREAD

**Issue by jundaychan** [Daxexs/flet-easy#16]
在v0.0.1我经常使用的是Viewsy

  # app_bar = ft.AppBar(
    #         title=ft.Image(src="baolaailogo.png",height=50),
    #         center_title=False,
    #         leading_width=40,
    #         bgcolor=ft.colors.SURFACE_VARIANT,
    #         actions=[
    #             ft.IconButton(ft.icons.WB_SUNNY_OUTLINED, on_click=theme),
    #             ft.PopupMenuButton(
    #                 items=[
    #                     ft.PopupMenuItem(text="🔥 Home", on_click=go_home),
    #                 ]
    #             ),
    #             ft.IconButton(ft.icons.TIPS_AND_UPDATES_OUTLINED, tooltip="去更新或者提出想法",
    #                           url=DOWNLOAD_URL),
    #         ],
    #     )

    # controls = [
    #     ft.Row(
    #     controls=[
    #         nav,
    #         ft.VerticalDivider(width=1),
    #     ],
    #     vertical_alignment=ft.CrossAxisAlignment.START,
    #     alignment=ft.MainAxisAlignment.START,
    #     expand=True
    # )]
    # page.appbar = app_bar

    #
    # return fs.Viewsy(
    #     navigation_bar=nav,
    #     appbar=app_bar,
    #     controls=controls,
    #     vertical_alignment=ft.MainAxisAlignment.START,
    #     horizontal_alignment=ft.CrossAxisAlignment.START,
    # )

def bar_builder(basic_view,gen_view, route: str):
    """
    侧边栏构建器
    :param view:
    :param route:
    :return:
    """
    basic_view.controls[0].controls.append(gen_view)
    # 通过拿到MENU_ITEMS的route是否等于传入的route来判断选中的是哪个导航
    for index, item in enumerate(MENU_ITEMS):
        if item.get('route') == route:
            basic_view.controls[0].controls[0].selected_index = index
    return basic_view.controls

然后在每个页面使用bar_builder

类似：@template_page.page(route="/")
def template(data: fs.Datasy):
    route = TemplateRoutes.MAIN_URL
    view = data.view
    controls = bar_builder(
        view,
        MyTemplate().build(),
        route
    )
    return ft.View(
        route,
        appbar=view.appbar,
        controls=controls,
        vertical_alignment=ft.MainAxisAlignment.START,
        horizontal_alignment=ft.CrossAxisAlignment.START,
    )

自从0.2.0之后，页面会出现两次了，所以我想问，在0.2.0什么是侧边栏的最佳实践？感谢作者的回答，你是一个非常好的开源作者

**Comment by jundaychan** [comment]
@app.config
def config(data: fs.Datasy):
    page = data.page
    page.title = "爆啦AI自动剪辑"
    page.window_min_width = 600
    page.window_min_height = 800
    theme = ft.Theme(font_family="Microsoft Yahei")
    theme.page_transitions.windows = ft.PageTransitionTheme.NONE
    
    
   报错：AttributeError: 'NoneType' object has no attribute 'title'

**Comment by jundaychan** [comment]
mabey use @app.config
def config(page: ft.Page):

not ft.data

**Comment by Daxexs** [comment]
> mabey use @app.config def config(page: ft.Page):
> 
> not ft.data

You are right, check the documentation for version 0.1.3 which is compatible with previous versions
* https://daxexs.github.io/flet-easy/0.1.3

According to the problem you present, here is the example: 
* https://daxexs.github.io/flet-easy/0.1.3/Customized-app/General-settings/
* https://daxexs.github.io/flet-easy/0.1.3/Customized-app/Control-view-configuration/

The `view` decorator is useful to reuse the properties of the flet `View` control in each of the pages that are created with the `flet-easy` `page` decorator, for example in the `flet` documentation these are the properties that can be used: https://flet.dev/docs/controls/view

**NOTE: `fs.Viewsy` is similar to `ft.View`**
