### ISSUE TITLE
Issues with pages being read twice again

### ISSUE THREAD

**Issue by jundaychan** [Daxexs/flet-easy#17]
like this

# mytemplate
@template_page.page(route="/")
def template(data: fs.Datasy):
    route = TemplateRoutes.MAIN_URL
    view = data.view
    controls = bar_builder(
        view,
        MyTemplate().build(),
        route
    )
    return ft.View(
        route,
        appbar=view.appbar,
        controls=controls,
        vertical_alignment=ft.MainAxisAlignment.START,
        horizontal_alignment=ft.CrossAxisAlignment.START,
    )

# barbuilder

import flet as ft
from flet_core import UserControl

from utils.menu_config import MENU_ITEMS

class Sidebar(UserControl):
    def __init__(self):
        super().__init__()
        # 侧边导航栏 NavigationRail
        self.nav = ft.NavigationRail(
            selected_index=0,
            label_type=ft.NavigationRailLabelType.ALL,
            min_extended_width=40,
            group_alignment=-0.9,
            # 定义在导航栏中排列的按钮项的外观，该值必须是两个或更多NavigationRailDestination实例的列表。
            # expand=True,
            destinations=[
                self.create_menu_item(**item) for item in MENU_ITEMS
            ],
            on_change=self.nav_change,
        )

    def create_menu_item(self, icon, selected_icon, label, tooltip,route):
        return ft.NavigationRailDestination(
            icon_content=ft.Icon(icon, tooltip=tooltip),
            selected_icon_content=ft.Icon(selected_icon),
            label=label,
        )
    def view(self):
        return self.nav

    def nav_change(self, e):
        """
        点左侧导航，刷新右侧内容（controls）
        :param e:
        :return:
        """
        selected_index = self.nav.selected_index
        selected_route = MENU_ITEMS[selected_index].get('route')
        e.page.go(selected_route)

def bar_builder(basic_view,gen_view, route: str):
    """
    侧边栏构建器
    :param view:
    :param route:
    :return:
    """
    basic_view.controls[0].controls.append(gen_view)
    # 通过拿到MENU_ITEMS的route是否等于传入的route来判断选中的是哪个导航
    for index, item in enumerate(MENU_ITEMS):
        if item.get('route') == route:
            basic_view.controls[0].controls[0].selected_index = index
    return basic_view.controls

# main 
UPDATE_URL = "https://hp.baolaai.com"
DOWNLOAD_URL = "https://hp.baolaai.com"
TITLE = "爆啦AI自动剪辑"
app = fs.FletEasy(route_init="/home")

@app.config
def config(page: ft.Page):
    page.title = "爆啦AI自动剪辑"
    page.window_min_width = 600
    page.window_min_height = 800

@app.view
def view(data: fs.Datasy):
    page = data.page
    def modify_theme():
        if page.theme_mode == ft.ThemeMode.DARK:
            page.theme_mode = ft.ThemeMode.LIGHT
        else:
            page.theme_mode = ft.ThemeMode.DARK

    def theme(e):
        if page.theme_mode == ft.ThemeMode.SYSTEM:
            modify_theme()
        modify_theme()
        page.update()

    def go_home(e):
        page.go(data.route_init)

    nav = Sidebar().view()
    app_bar = ft.AppBar(
            title=ft.Image(src="baolaailogo.png",height=50),
            center_title=False,
            leading_width=40,
            bgcolor=ft.colors.SURFACE_VARIANT,
            actions=[
                ft.IconButton(ft.icons.WB_SUNNY_OUTLINED, on_click=theme),
                ft.PopupMenuButton(
                    items=[
                        ft.PopupMenuItem(text="🔥 Home", on_click=go_home),
                    ]
                ),
                ft.IconButton(ft.icons.TIPS_AND_UPDATES_OUTLINED, tooltip="去更新或者提出想法",
                              url=DOWNLOAD_URL),
            ],
        )

    controls = [
        ft.Row(
        controls=[
            nav,
            ft.VerticalDivider(width=1),
        ],
        vertical_alignment=ft.CrossAxisAlignment.START,
        alignment=ft.MainAxisAlignment.START,
        expand=True
    )]
    page.appbar = app_bar

    return fs.Viewsy(
        navigation_bar=nav,
        appbar=app_bar,
        controls=controls,
        vertical_alignment=ft.MainAxisAlignment.START,
        horizontal_alignment=ft.CrossAxisAlignment.START,
    )

app.add_pages(baola_routes)

app.run()

**Comment by xzripper** [comment]
Try <a href="https://github.com/xzripper/flet_navigator">`flet_navigator`</a>

**Comment by Daxexs** [comment]
> como esto
> # mi plantilla
> 
> @template_page.page(ruta="/") plantilla def (datos: fs.Datasy): ruta = TemplateRoutes.MAIN_URL vista = datos.vista controles = bar_builder( vista, MiPlantilla().build(), ruta ) volver pies.Ver( ruta, barra de aplicaciones = ver.barra de aplicaciones, controles = controles, vertical_alignment=ft.MainAxisAlignment.START, horizontal_alignment=ft.CrossAxisAlignment.START, )
> # constructor de bares
> 
> importar flet como pies desde flet_core importar UserControl
> 
> desde utils.menu_config importar MENU_ITEMS
> 
> barra lateral de clase (Control de usuario): def ** inicio ** (yo): súper(). ** en eso ** () # Barra de navegación lateralNavigationRail self.nav = ft.NavigationRail( índice_seleccionado = 0, label_type=ft.NavigationRailLabelType.ALL, min_extended_width=40, alineación_grupo=-0.9, # Definir la apariencia de los elementos de los botones dispuestos en la barra de navegación. Este valor debe ser una lista de dos o más instancias de NavigationRailDestination. # expandir=Verdadero, destinos=[ self.create_menu_item(**item) para el elemento en MENU_ITEMS ], on_change=self.nav_change, )
> 
> ```
> def create_menu_item(self, icon, selected_icon, label, tooltip,route):
>     return ft.NavigationRailDestination(
>         icon_content=ft.Icon(icon, tooltip=tooltip),
>         selected_icon_content=ft.Icon(selected_icon),
>         label=label,
>     )
> def view(self):
>     return self.nav
> 
> def nav_change(self, e):
>     """
>     点左侧导航，刷新右侧内容（controls）
>     :param e:
>     :return:
>     """
>     selected_index = self.nav.selected_index
>     selected_route = MENU_ITEMS[selected_index].get('route')
>     e.page.go(selected_route)
> ```
> 
> def bar_builder(vista_básica,vista_gen, ruta: cadena): """ Constructor de barra lateral :vista de parámetros: :ruta del parámetro: :devolver: """ basic_view.controls[0].controls.append(gen_view) # Determinar qué navegación se selecciona obteniendo si la ruta de MENU_ITEMS es igual a la ruta entrante para índice, elemento en enumerar (MENU_ITEMS): si item.get('ruta') == ruta: basic_view.controls[0].controls[0].selected_index = índice devolver basic_view.controls
> # principal
> 
> UPDATE_URL = " [ https://hp.baolaai.com ](https://hp.baolaai.com) " DOWNLOAD_URL = " [ https://hp.baolaai.com ](https://hp.baolaai.com) " TITLE = "Edición automática de Bola AI" aplicación = fs.FletEasy(route_init="/home")
> 
> @aplicación.config def config(página: ft.Página): page.title = "Edición automática de Bola AI" página.window_min_width = 600 página.window_min_height = 800
> 
> @aplicación.vista vista def (datos: fs.Datasy): página = datos.página def modificar_tema(): si page.theme_mode == ft.ThemeMode.DARK: page.theme_mode = ft.ThemeMode.LIGHT demás: page.theme_mode = ft.ThemeMode.DARK
> 
> ```
> def theme(e):
>     if page.theme_mode == ft.ThemeMode.SYSTEM:
>         modify_theme()
>     modify_theme()
>     page.update()
> 
> def go_home(e):
>     page.go(data.route_init)
> 
> nav = Sidebar().view()
> app_bar = ft.AppBar(
>         title=ft.Image(src="baolaailogo.png",height=50),
>         center_title=False,
>         leading_width=40,
>         bgcolor=ft.colors.SURFACE_VARIANT,
>         actions=[
>             ft.IconButton(ft.icons.WB_SUNNY_OUTLINED, on_click=theme),
>             ft.PopupMenuButton(
>                 items=[
>                     ft.PopupMenuItem(text="🔥 Home", on_click=go_home),
>                 ]
>             ),
>             ft.IconButton(ft.icons.TIPS_AND_UPDATES_OUTLINED, tooltip="去更新或者提出想法",
>                           url=DOWNLOAD_URL),
>         ],
>     )
> 
> controls = [
>     ft.Row(
>     controls=[
>         nav,
>         ft.VerticalDivider(width=1),
>     ],
>     vertical_alignment=ft.CrossAxisAlignment.START,
>     alignment=ft.MainAxisAlignment.START,
>     expand=True
> )]
> page.appbar = app_bar
> 
> 
> return fs.Viewsy(
>     navigation_bar=nav,
>     appbar=app_bar,
>     controls=controls,
>     vertical_alignment=ft.MainAxisAlignment.START,
>     horizontal_alignment=ft.CrossAxisAlignment.START,
> )
> ```
> 
> aplicación.add_pages(baola_routes)
> 
> app.run()

Could you please provide the app code more clearly what causes the error.
**NOTE** : If you are on version 0.2.0, upgrade to version 0.2.1
